# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbfilestorage', '0006_remove_dbfile_filehash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfile',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
