# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbfilestorage', '0006_remove_dbfile_filehash'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbfile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbfile',
            name='primary_key',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dbfile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
